version: "3"
services:
  app:
    image: nightfuryest/angular-prod:latest
    volumes:
      - app:/var/www
    networks:
      - default
      - traefik-public
    links:
      - database
    deploy:
      labels:
        - traefik.frontend.rule=Host:${APP_DOMAIN?Variable APP_DOMAIN not set}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
volumes:
  app:
networks:
  traefik-public:
    external: true
